### ISSUE TITLE
Link to the wiki

### ISSUE THREAD

**Issue by Raphael-Boichot** [bitbank2/PNGenc#13]
Hello.

I'm trying to use your library on Pi Pico but I'm running with some bugs on the payload lenght. I would like to rule out any syntax issue.
Could you restore the link to the wiki ?

Thanks !

**Comment by bitbank2** [comment]
Restore what wiki link? I can access it from this github page above.

What bugs are you encountering?

**Comment by Raphael-Boichot** [comment]
Oh, got it, sorry.

Typically I got a data lenght different (shorter) from the width*height at decompression, but only for "big" images (more than 500x500 pixels).
I did not have the issue on ESP32 but with a slighly different call, so I would like to continue tests.
