### ISSUE TITLE
Missing data in compressed stream

### ISSUE THREAD

**Issue by Raphael-Boichot** [bitbank2/PNGenc#14]
Hello again.

So, I'm using the library on Pi Pico to record the stream from a camera to SD card. For some reason I need to upscale images between 2x and 10x and I deal with that during encoding. I can process pretty large images.

What I get is confusing. On the same run, continuously recording, I can get perfect images like this : 
![clean](https://user-images.githubusercontent.com/63796796/234344527-4235f427-a489-44fc-bddb-b85320fe8eae.png)

Or completely broken images like these:
![truncated_1](https://user-images.githubusercontent.com/63796796/234344628-1c0d0d21-f500-4f71-b3b9-5f887a036d21.png)
![Truncated_2](https://user-images.githubusercontent.com/63796796/234344632-26211b5a-53ee-4c9c-8bdf-7ded6b616f44.png)

Broken images have always too short uncompressed data compared to WIDTH*HEIGHT. 
I've checked the image with https://www.nayuki.io/page/png-file-chunk-inspector and the error is always the same, but data can be more or less damaged.

Do you have an idea of what could be the error and side question: can I bound the memory usage during the call ? I indeed suspect memory issues even I I have plenty of memory left after compiling (about 60 extra kB).

**Comment by Raphael-Boichot** [comment]
![image](https://user-images.githubusercontent.com/63796796/234346699-be21f938-e7f2-4759-a62c-4069dce59a4e.png)
Here the typical error. There is no pattern between images. I've tried different upscaling factors, different compression levels, different palettes, it's overall always the same.

**Comment by bitbank2** [comment]
I'll take a look

**Comment by Raphael-Boichot** [comment]
Some more infos: if I write single color image, no problem. If I upscale a fully random image, it's getting worse:
![0008117](https://user-images.githubusercontent.com/63796796/234367103-dbff5ee6-03c0-4918-8574-b1222de91e41.png)

So the issue depends on the complexity of the data to encode.

**Comment by Raphael-Boichot** [comment]
![0008163](https://user-images.githubusercontent.com/63796796/234371097-63a7695b-d021-46bd-b82d-8800dd014fbd.png)

But this works, strange... Maybe my upscaler code is triggering some issue

**Comment by Raphael-Boichot** [comment]
OK, I got the issue: when png.addLine(ucLine) is repeated several times with the same data, the code has unexpected output. Here's a minimal code to reproduce the bug :
[code.txt](https://github.com/bitbank2/PNGenc/files/11325998/code.txt)

It appears only at certain resolutions and for certain compressing levels
![0008193](https://user-images.githubusercontent.com/63796796/234379806-0903fdbb-d53c-4c0f-91e4-b1a25878c7fc.png)

**Comment by Raphael-Boichot** [comment]
After some more tests, I think this is an issue with the filesystem or some variable initialization. The first image is always good whatever the used parameters and the issue appears always after consecutive recordings.
Looks like something is not initialized again at the end of conversion/writing. If I soft reboot the Pi pico, first image is good again.

**Comment by Raphael-Boichot** [comment]
Problem fixed: incompatibility between PNGenc and my TFT library
