### ISSUE TITLE
Column by column generation

### ISSUE THREAD

**Issue by wired8** [bitbank2/PNGenc#15]
Hi @bitbank2, first off great library.  I'm attempting to generate an audio waveform image of a large wav file on an esp32.  I'm wondering if it's possible to add a method for drawing a png by column rather than by line?

**Comment by bitbank2** [comment]
I'm glad you like it. PNGs are encoded one line at a time. If you want to treat them as columns then the only idea I can think of is to rotate your images 90 degrees and then draw each line as if it's a column. There's no other reasonable way I can think of unless you decode the entire image and manage the columns aftwards.
