### ISSUE TITLE
crc error in images bigger than the test image

### ISSUE THREAD

**Issue by Raphael-Boichot** [bitbank2/PNGenc#2]
Hello.

I'm now able to use the test case on ESP and it works great with a 128x128 image (can be open with any image editor).
Now If I increase the size to 256x256 (for example), the image is still generated but I cannot open the file with some image editor. Here is the output of pngcheck:

PS E:\> .\pngcheck.win64.exe -cvt testimg.png
File: ←[40;37;1mtestimg.png←[0m (5350 bytes)
  chunk ←[40;33mIHDR←[0m at offset 0x0000c, length 13
    256 x 256 image, 8-bit palette, non-interlaced
  chunk ←[40;33mPLTE←[0m at offset 0x00025, length 768: 256 palette entries
  chunk ←[40;33mtRNS←[0m at offset 0x00331, length 256: 256 transparency entries
  chunk ←[40;33mIDAT←[0m at offset 0x0043d, length 4245
    zlib: deflated, 4K window, fast compression
  CRC error in chunk IDAT (computed 1062a5e5, expected 032c8ffa)
←[40;31;1mERRORS DETECTED←[0m in testimg.png

![testimg](https://user-images.githubusercontent.com/63796796/140066633-a4c52b90-c152-4bd1-8300-1bd91134bcb7.png)

Do you have an idea of what gone wrong with crc ?

Raphael.

**Comment by Raphael-Boichot** [comment]
If I change the crc in image from 032c8ffa to1062a5e5 manually in hex editor, the image is OK whatever the image editor and pngcheck do not detect any error. Seems there is a crc calculation error for long files...

**Comment by Raphael-Boichot** [comment]
After some more investigations, the bug happens when the IDAT size becomes superior to PNG_FILE_BUF_SIZE. The passing of several data buffer packets (more than one at least) to PNGCalcCRC returns a wrong CRC. One packet is OK in the other hand.

**Comment by bitbank2** [comment]
You're right, I need to fix the logic to emit IDAT chunks each time the PNG_FILE_BUF gets full. The logic currently works for when you allocate a full sized output buffer, but not when it writes incrementally.

**Comment by Raphael-Boichot** [comment]
Bug found. Just do ulCRC=ulCRC ^ 0xffffffffL; out of PNGCalcCRC and that's it ! You can pass as many packets as you wish now. So last line of PNGCalcCRC becomes just return crc; and the 1 complement is made outside at the end just before writing the CRC.

**Comment by bitbank2** [comment]
Would you mind doing a pull request to get your fix in?

**Comment by Raphael-Boichot** [comment]
Will prepare this by tomorrow.
