### ISSUE TITLE
RGB565 to PNG

### ISSUE THREAD

**Issue by weilunisme798** [bitbank2/PNGenc#5]
Hi, Sir I was trying to use your library to convert my RGB565 to PNG, but I do not know what is the parameter value for addRGB565Line(uint16_t *pPixels, void ***_pTempLine_**); what does pTempLine means?
Maybe you can share an example for RGB565 to PNG.
Thank you

**Comment by bitbank2** [comment]
This library is designed to use as little memory as possible and to never call malloc. For this reason, you need to give it a buffer to receive the converted pixels. So... if you are going from RGB565->TrueColor (24-bpp), then you need 3*Width bytes in the temporary buffer you pass. If you're converting from RGB565 to grayscale, then you only need Width bytes.
