### ISSUE TITLE
Future PR for Arduino Portenta PNG to SD Card

### ISSUE THREAD

**Issue by hpssjellis** [bitbank2/PNGenc#6]
Hi Larry
From Twitter @rocksetta (Jeremy Ellis).

Not sure if you are taking PR's for this library, but I am trying to write a sketch for the Arduino Portenta with Vision Shield that would save a 320x320 x1 grayscale PNG image to the onboard SD card. It should be doable since I have camera working code, SD card saving code and your library.

I just want to be able to save a PNG image to the SD card every 30 seconds. If I get it working are you interested in accepting PR's or should I just put it on my own library?

I have forked your library and will put my drafts and main, eventually working code at [portenta-camera-png-sdcard](https://github.com/hpssjellis/PNGenc/tree/master/examples/portenta-camera-png-sdcard)

Any opinions are welcome.

**Comment by bitbank2** [comment]
Hi Jeremy,
I'm definitely accepting PRs for all of my libraries (that's part of the reason they're public). If you're proposing to add a new example sketch - definitely. If you want to add functions/features, then we should probably chat about it before you spend too much time so that we're aligned on the goal.

**Comment by hpssjellis** [comment]
I think your library is good to go, I just have to workout the differences from your example with the Portenta SD card file saving process, and figure out the Camera frame_buffer single byte grayscale to PNG, which I think your library is pre-set to deal with.

**Comment by bitbank2** [comment]
Yes, you shouldn't need to make any changes to the library to do what you need.
